x-common-variables: &env_vars
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_DB: ${DATABASE_DB}
  ENVIRONMENT: ${ENVIRONMENT}
  LOG_LEVEL: ${LOG_LEVEL}
  S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
  S3_BUCKET: ${S3_BUCKET}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  MISTRAL_API_KEY: ${MISTRAL_API_KEY}
  QDRANT_HOST: ${QDRANT_HOST}
  QDRANT_PORT: ${QDRANT_PORT}
  QDRANT_VECTOR_DIMS: ${QDRANT_VECTOR_DIMS}
  REDIS_URL: ${REDIS_URL}
  YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}

name: ytkb

services:
  proxy:
    image: caddy:2.11.4-alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "${APP_PORT_HTTPS}:443"
      - "${APP_PORT_HTTP}:80"
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
      - exclude_fe:/usr/src/app/node_modules

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: sh -c "./wait-for-it.sh postgres:5432 -t 30 && ./wait-for-it.sh redis:6379 && ./wait-for-it.sh qdrant:6333 && ./wait-for-it.sh minio:9000 && make api"
    restart: unless-stopped
    volumes:
      - ./backend:/usr/src/app
      - .env:/usr/src/app/.env
      - exclude_api:/usr/src/app/.venv
    depends_on:
      - postgres
      - migrate  
      - redis
      - minio
      - qdrant    
    environment: *env_vars

  worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: sh -c "./wait-for-it.sh postgres:5432 -t 30 && ./wait-for-it.sh redis:6379 && ./wait-for-it.sh qdrant:6333 && ./wait-for-it.sh minio:9000 && make worker"
    deploy:
      mode: replicated
      replicas: 4
    restart: unless-stopped
    volumes:
      - ./backend:/usr/src/app
      - .env:/usr/src/app/.env
      - exclude_api:/usr/src/app/.venv
    depends_on:
      - postgres
      - migrate  
      - redis
      - minio
      - qdrant    
    environment: *env_vars

  migrate:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: sh -c "./wait-for-it.sh postgres:5432 -t 30 && make migrate"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - .env:/usr/src/app/.env
      - exclude_api:/usr/src/app/.venv
    environment: *env_vars

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    restart: unless-stopped
    ports:
      - "${MINIO_BACKEND_PORT}:9000"
      - "${MINIO_FRONTEND_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:18.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "${DATABASE_EXPOSED_PORT}:5432"

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "${QDRANT_EXPOSED_PORT}:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7.4.11-alpine3.21
    restart: unless-stopped
    ports:
      - "${REDIS_EXPOSED_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  exclude_fe:
  exclude_api:
  caddy_data:
  caddy_config:
  postgres_data:
  minio_data:
  chroma_data:
  redis_data:
  qdrant_data:

networks:
  default:
    name: ytkb_shared