"""empty message

Revision ID: 086f46388607
Revises: 5c5f494af67e
Create Date: 2026-09-27 11:42:10.576362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086f46388607'
down_revision: Union[str, Sequence[str], None] = '5c5f494af67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_videos__video_chunks_video_id'), 'videos__video_chunks', ['video_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_videos__video_chunks_video_id'), 'videos__video_chunks', type_='unique')
    # ### end Alembic commands ###
