"""empty message

Revision ID: 1248a6666ec3
Revises: 20f0275609bc
Create Date: 2026-09-25 11:22:36.048454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1248a6666ec3'
down_revision: Union[str, Sequence[str], None] = '20f0275609bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos__channels', sa.Column('handle', sa.String(length=100), nullable=False))
    op.create_unique_constraint(op.f('uq_videos__channels_handle'), 'videos__channels', ['handle'])
    op.create_unique_constraint(op.f('uq_videos__channels_url'), 'videos__channels', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_videos__channels_url'), 'videos__channels', type_='unique')
    op.drop_constraint(op.f('uq_videos__channels_handle'), 'videos__channels', type_='unique')
    op.drop_column('videos__channels', 'handle')
    # ### end Alembic commands ###
