"""empty message

Revision ID: 256115680785
Revises: 086f46388607
Create Date: 2026-09-27 16:29:15.064847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256115680785'
down_revision: Union[str, Sequence[str], None] = '086f46388607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos__video_chunks', sa.Column('content_with_timestamps', sa.String(), nullable=True))
    op.add_column('videos__video_chunks', sa.Column('content_without_timestamps', sa.String(), nullable=True))
    op.drop_column('videos__video_chunks', 'content')
    op.add_column('videos__videos', sa.Column('content_with_timestamps', sa.String(), nullable=True))
    op.add_column('videos__videos', sa.Column('content_without_timestamps', sa.String(), nullable=True))
    op.drop_column('videos__videos', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos__videos', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('videos__videos', 'content_without_timestamps')
    op.drop_column('videos__videos', 'content_with_timestamps')
    op.add_column('videos__video_chunks', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('videos__video_chunks', 'content_without_timestamps')
    op.drop_column('videos__video_chunks', 'content_with_timestamps')
    # ### end Alembic commands ###
