"""empty message

Revision ID: 4fd0f3153d4f
Revises: 900274d6ef2b
Create Date: 2026-09-27 20:44:41.981698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fd0f3153d4f'
down_revision: Union[str, Sequence[str], None] = '900274d6ef2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion__video_queue', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('ingestion__video_queue', 'next_attemp_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion__video_queue', sa.Column('next_attemp_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('ingestion__video_queue', 'next_attempt_at')
    # ### end Alembic commands ###
