"""empty message

Revision ID: 527d09b938d5
Revises: c0f9f7d5ccbf
Create Date: 2026-09-27 11:27:59.375361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527d09b938d5'
down_revision: Union[str, Sequence[str], None] = 'c0f9f7d5ccbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos__video_chunks', sa.Column('audio_file_s3_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos__video_chunks', 'audio_file_s3_key')
    # ### end Alembic commands ###
