"""empty message

Revision ID: 56eb5173669e
Revises: e639f3e4ea3d
Create Date: 2026-09-28 09:34:45.001497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56eb5173669e'
down_revision: Union[str, Sequence[str], None] = 'e639f3e4ea3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion__video_queue', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion__video_queue', sa.Column('claimed_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion__video_queue', 'claimed_until')
    op.drop_column('ingestion__video_queue', 'claimed_at')
    # ### end Alembic commands ###
