"""empty message

Revision ID: 6c7bf64b1d56
Revises: c1c85f8f924b
Create Date: 2026-09-28 20:19:43.821775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7bf64b1d56'
down_revision: Union[str, Sequence[str], None] = 'c1c85f8f924b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion__step_runs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion__step_runs', 'created_at')
    # ### end Alembic commands ###
