"""empty message

Revision ID: 7ac50a45bff2
Revises: 8760a80de9c1
Create Date: 2026-10-01 05:17:14.415213

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

video_status = postgresql.ENUM("DRAFT", "PUBLISHED", name="video_status")


# revision identifiers, used by Alembic.
revision: str = '7ac50a45bff2'
down_revision: Union[str, Sequence[str], None] = '8760a80de9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    video_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "videos__videos",
        sa.Column("status", video_status, server_default="DRAFT", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos__videos", "status")
    video_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
