"""empty message

Revision ID: 7f5ae819cd38
Revises: 
Create Date: 2026-09-25 07:52:16.099944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5ae819cd38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos__channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos__channels'))
    )
    op.create_table('videos__videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['videos__channels.id'], name=op.f('fk_videos__videos_channel_id_videos__channels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos__videos'))
    )
    op.create_table('videos__video_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos__videos.id'], name=op.f('fk_videos__video_chunks_video_id_videos__videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos__video_chunks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos__video_chunks')
    op.drop_table('videos__videos')
    op.drop_table('videos__channels')
    # ### end Alembic commands ###
