"""empty message

Revision ID: 8760a80de9c1
Revises: 98df6e98302e
Create Date: 2026-09-30 20:38:56.499351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8760a80de9c1'
down_revision: Union[str, Sequence[str], None] = '98df6e98302e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos__videos', 'video_file_s3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos__videos', sa.Column('video_file_s3_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
