"""empty message

Revision ID: 900274d6ef2b
Revises: 256115680785
Create Date: 2026-09-27 20:44:19.155799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900274d6ef2b'
down_revision: Union[str, Sequence[str], None] = '256115680785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion__video_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attemp_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos__videos.id'], name=op.f('fk_ingestion__video_queue_video_id_videos__videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion__video_queue'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion__video_queue')
    # ### end Alembic commands ###
