"""empty message

Revision ID: 96ea64836546
Revises: a8145ebf298c
Create Date: 2026-09-25 14:05:14.400748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ea64836546'
down_revision: Union[str, Sequence[str], None] = 'a8145ebf298c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos__videos', sa.Column('youtube_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(op.f('uq_videos__videos_youtube_id'), 'videos__videos', ['youtube_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_videos__videos_youtube_id'), 'videos__videos', type_='unique')
    op.drop_column('videos__videos', 'youtube_id')
    # ### end Alembic commands ###
