"""empty message

Revision ID: 98df6e98302e
Revises: 6c7bf64b1d56
Create Date: 2026-09-29 21:34:55.103087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98df6e98302e'
down_revision: Union[str, Sequence[str], None] = '6c7bf64b1d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion__video_queue')
    op.drop_table('ingestion__video_pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion__video_pipeline',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage', postgresql.ENUM('DOWNLOAD', 'CHUNK', 'TRANSCRIBE', 'EMBED', 'INDEX', name='pipeline_stage'), server_default=sa.text("'DOWNLOAD'::pipeline_stage"), autoincrement=False, nullable=False),
    sa.Column('stage_status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED', name='pipeline_stage_status'), server_default=sa.text("'PENDING'::pipeline_stage_status"), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos__videos.id'], name=op.f('fk_ingestion__video_pipeline_video_id_videos__videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion__video_pipeline'))
    )
    op.create_table('ingestion__video_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('claimed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('claimed_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos__videos.id'], name=op.f('fk_ingestion__video_queue_video_id_videos__videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion__video_queue'))
    )
    # ### end Alembic commands ###
