"""empty message

Revision ID: c0f9f7d5ccbf
Revises: 011514a33802
Create Date: 2026-09-27 10:58:22.482949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f9f7d5ccbf'
down_revision: Union[str, Sequence[str], None] = '011514a33802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos__videos', sa.Column('video_file_s3_key', sa.String(length=200), nullable=True))
    op.add_column('videos__videos', sa.Column('audio_file_s3_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos__videos', 'audio_file_s3_key')
    op.drop_column('videos__videos', 'video_file_s3_key')
    # ### end Alembic commands ###
