"""empty message

Revision ID: e639f3e4ea3d
Revises: 4fd0f3153d4f
Create Date: 2026-09-27 21:11:20.948565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e639f3e4ea3d'
down_revision: Union[str, Sequence[str], None] = '4fd0f3153d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion__video_pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('DOWNLOAD', 'CHUNK', 'TRANSCRIBE', 'EMBED', 'INDEX', name='pipeline_stage'), server_default='DOWNLOAD', nullable=False),
    sa.Column('stage_status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED', name='pipeline_stage_status'), server_default='PENDING', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos__videos.id'], name=op.f('fk_ingestion__video_pipeline_video_id_videos__videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion__video_pipeline'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion__video_pipeline')
    # ### end Alembic commands ###
